# Autogenerated by nbdev

d = { 'settings': { 'branch': 'released',
                'doc_baseurl': '/mhar',
                'doc_host': 'https://sonder-art.github.io',
                'git_url': 'https://github.com/sonder-art/mhar',
                'lib_path': 'mhar'},
  'syms': {'mhar.core': {'mhar.core.foo': ('core.html#foo', 'mhar/core.py')}}}
