# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_polytope_examples.ipynb.

# %% auto 0
__all__ = ['Hypercube']

# %% ../nbs/04_polytope_examples.ipynb 2
import torch

from .polytope import Polytope, NFDPolytope
from .inner_point import ChebyshevCenter

# %% ../nbs/04_polytope_examples.ipynb 3
class Hypercube(Polytope):
    
    def __init__(self,
                 n:int=None,
                 dtype=torch.float16, 
                 copy: bool = False, 
                 requires_grad: bool = False) -> None:
        
        A_in = torch.cat((torch.eye(n), torch.eye(n) * -1.0), dim=0).to(dtype)
        b_in = torch.ones(2 * n, dtype=torch.float32).view(-1, 1)        
        super().__init__(A_in, b_in, dtype, copy, requires_grad)
